name: 'Test LLM outputs'
description: 'Automatically run a before/after comparison of edited prompts and posts the result to your Pull Request.'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  github-token:
    description: 'Github Token, used to add comments to the PR'
    required: true
  prompts:
    description: 'List of prompt files to watch'
    required: true
  config:
    description: 'Path to a promptfoo config file'
    required: true
  cache-path:
    description: 'Path to cache directory'
    required: false
  openai-api-key:
    description: 'OpenAI API Key'
    required: false
  azure-openai-api-key:
    description: 'Azure OpenAI API Key'
    required: false
branding:
  icon: 'box'
  color: 'yellow'
