name: 'Test LLM outputs'
description: 'Run promptfoo evaluations on your prompts. Works with pull requests, pushes, and manual triggers (workflow_dispatch).'
runs:
  using: 'node20'
  main: 'dist/index.js'
# For workflow_dispatch events, you can use the following inputs in your workflow:
# - inputs.files: Newline-separated list of files to evaluate (optional)
# - inputs.base: Base branch/commit to compare against (default: HEAD~1) (optional)
#
# Example workflow_dispatch configuration:
# on:
#   workflow_dispatch:
#     inputs:
#       files:
#         description: 'Files to evaluate (leave empty to auto-detect)'
#         required: false
#         type: string
#       base:
#         description: 'Base branch/commit to compare against'
#         required: false
#         default: 'HEAD~1'
#         type: string
inputs:
  github-token:
    description: 'Github Token, used to add comments to PRs and write workflow summaries'
    required: true
  prompts:
    description: 'List of prompt files to watch (glob patterns supported, one per line)'
    required: false
  config:
    description: 'Path to a promptfoo config file'
    required: true
  cache-path:
    description: 'Path to cache directory'
    required: false
  openai-api-key:
    description: 'OpenAI API Key (falls back to OPENAI_API_KEY environment variable)'
    required: false
  azure-api-key:
    description: 'Azure API key (falls back to AZURE_OPENAI_API_KEY environment variable)'
    required: false
  anthropic-api-key:
    description: 'Anthropic API key (falls back to ANTHROPIC_API_KEY environment variable)'
    required: false
  huggingface-api-key:
    description: 'Huggingface API key (falls back to HF_API_TOKEN environment variable)'
    required: false
  aws-access-key-id:
    description: 'AWS Access Key ID (falls back to AWS_ACCESS_KEY_ID environment variable)'
    required: false
  aws-secret-access-key:
    description: 'AWS Secret Access Key (falls back to AWS_SECRET_ACCESS_KEY environment variable)'
    required: false
  replicate-api-key:
    description: 'Replicate API key'
    required: false
  palm-api-key:
    description: 'Palm API key'
    required: false
  vertex-api-key:
    description: 'Google vertex API key'
    required: false
  cohere-api-key:
    description: 'Cohere API key'
    required: false
  mistral-api-key:
    description: 'Mistral API key'
    required: false
  groq-api-key:
    description: 'Groq API key'
    required: false
  promptfoo-version:
    description: 'Version of promptfoo to use'
    required: false
    default: 'latest'
  working-directory:
    description: 'The working directory to run promptfoo in'
    required: false
    default: '.'
  no-share:
    description: 'Do not share the promptfoo result'
    required: false
    default: 'false'
  use-config-prompts:
    description: 'Use prompts from config file'
    required: false
    default: 'false'
  env-files:
    description: 'Comma-separated list of .env files to load (e.g. ".env,.env.test.local")'
    required: false
    default: ''
  fail-on-threshold:
    description: 'Fail the action if the evaluation success rate is below this percentage (0-100)'
    required: false
    default: ''
  debug:
    description: 'Enable debug logging for troubleshooting'
    required: false
    default: 'false'
  max-concurrency:
    description: 'Maximum number of concurrent API calls (default: 4)'
    required: false
    default: '4'
  no-table:
    description: 'Run promptfoo with --no-table flag to keep output minimal'
    required: false
    default: 'false'
  no-progress-bar:
    description: 'Run promptfoo with --no-progress-bar flag to keep output minimal'
    required: false
    default: 'false'
  disable-comment:
    description: 'Disable posting comments to the PR'
    required: false
    default: 'false'
  workflow-files:
    description: 'Files to evaluate in workflow_dispatch mode (newline-separated list). If not specified, falls back to workflow inputs or auto-detection.'
    required: false
    default: ''
  workflow-base:
    description: 'Base ref to compare against in workflow_dispatch mode (e.g., main, HEAD~1). If not specified, falls back to workflow inputs or HEAD~1.'
    required: false
    default: ''
branding:
  icon: 'box'
  color: 'yellow'
