import * as dotenv from 'dotenv';
import { ErrorCodes, PromptfooActionError } from './errors';

// Variables that let a repository-controlled env file execute code, redirect an
// inherited provider credential, or change the action's pass/fail/filesystem
// behavior. Keep this explicit and grouped so the trust boundary is easy
// to audit. Legitimate overrides belong in the trusted workflow environment.
const FORBIDDEN_ENV_FILE_KEYS = new Set([
  'ABLIT_API_BASE_URL',
  'AI21_API_BASE_URL',
  'ALL_PROXY',
  'ANTHROPIC_AUTH_TOKEN',
  'ANTHROPIC_BASE_URL',
  'ANTHROPIC_CONFIG_DIR',
  'ANTHROPIC_CUSTOM_HEADERS',
  'ANTHROPIC_ENVIRONMENT_ID',
  'ANTHROPIC_ENVIRONMENT_KEY',
  'ANTHROPIC_FEDERATION_RULE_ID',
  'ANTHROPIC_IDENTITY_TOKEN',
  'ANTHROPIC_IDENTITY_TOKEN_FILE',
  'ANTHROPIC_ORGANIZATION_ID',
  'ANTHROPIC_PROFILE',
  'ANTHROPIC_SCOPE',
  'ANTHROPIC_SERVICE_ACCOUNT_ID',
  'ANTHROPIC_WORKSPACE_ID',
  'API_HOST',
  'APPDATA',
  'AWS_BEARER_TOKEN_BEDROCK',
  'AWS_BEDROCK_BASE_URL',
  'AWS_BEDROCK_REGION',
  'AWS_CA_BUNDLE',
  'AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE',
  'AWS_CONTAINER_CREDENTIALS_FULL_URI',
  'AWS_CONTAINER_CREDENTIALS_RELATIVE_URI',
  'AWS_CONFIG_FILE',
  'AWS_DEFAULT_PROFILE',
  'AWS_DEFAULT_REGION',
  'AWS_EC2_METADATA_SERVICE_ENDPOINT',
  'AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE',
  'AWS_ENDPOINT_URL',
  'AWS_LOGIN_CACHE_DIRECTORY',
  'AWS_PROFILE',
  'AWS_REGION',
  'AWS_ROLE_ARN',
  'AWS_ROLE_SESSION_NAME',
  'AWS_SHARED_CREDENTIALS_FILE',
  'AWS_WEB_IDENTITY_TOKEN_FILE',
  'AZURE_ADDITIONALLY_ALLOWED_TENANTS',
  'AZURE_AI_PROJECT_URL',
  'AZURE_API_BASE_URL',
  'AZURE_API_HOST',
  'AZURE_AUTHORITY_HOST',
  'AZURE_CLIENT_CERTIFICATE_PATH',
  'AZURE_CLIENT_ID',
  'AZURE_CONTENT_SAFETY_ENDPOINT',
  'AZURE_FEDERATED_TOKEN_FILE',
  'AZURE_OPENAI_API_BASE_URL',
  'AZURE_OPENAI_API_HOST',
  'AZURE_OPENAI_BASE_URL',
  'AZURE_OPENAI_ENDPOINT',
  'AZURE_POD_IDENTITY_AUTHORITY_HOST',
  'AZURE_REGIONAL_AUTHORITY_NAME',
  'AZURE_STORAGE_CONNECTION_STRING',
  'AZURE_TENANT_ID',
  'AZURE_TOKEN_CREDENTIALS',
  'AZURE_TOKEN_SCOPE',
  'AR',
  'AR_HOST',
  'AR_TARGET',
  'BASH_ENV',
  'CDP_DOMAIN',
  'CC',
  'CC_HOST',
  'CC_TARGET',
  'CGO_CFLAGS',
  'CGO_CPPFLAGS',
  'CGO_CXXFLAGS',
  'CGO_LDFLAGS',
  'CI',
  'CFLAGS',
  'CFLAGS_HOST',
  'CLAUDE_CODE_USE_BEDROCK',
  'CLAUDE_CODE_USE_VERTEX',
  'CLAUDE_CONFIG_DIR',
  'CLAWDBOT_GATEWAY_URL',
  'CLOUDFLARE_ACCOUNT_ID',
  'CLOUDFLARE_GATEWAY_ID',
  'COMPILER_PATH',
  'CODEX_HOME',
  'COMSPEC',
  'CURL_CA_BUNDLE',
  'CPATH',
  'CPPFLAGS',
  'CPPFLAGS_HOST',
  'CPLUS_INCLUDE_PATH',
  'C_INCLUDE_PATH',
  'CXX',
  'CXX_HOST',
  'CXX_TARGET',
  'CXXFLAGS',
  'CXXFLAGS_HOST',
  'DATABRICKS_WORKSPACE_URL',
  'DOCKER_MODEL_RUNNER_BASE_URL',
  'DOTENV_KEY',
  'ENVOY_API_BASE_URL',
  'ENV',
  'FIREWORKS_API_BASE_URL',
  'FC',
  'GCCGO',
  'GCCGOTOOLDIR',
  'GCC_EXEC_PREFIX',
  'GCLOUD_PROJECT',
  'GCE_METADATA_HOST',
  'GCE_METADATA_IP',
  'GEM_HOME',
  'GEM_PATH',
  'GEM_SPEC_CACHE',
  'GENAI_ENDPOINT',
  'GOAUTH',
  'GOBIN',
  'GOCACHE',
  'GOCACHEPROG',
  'GOCOVERDIR',
  'GODEBUG',
  'GOENV',
  'GOFLAGS',
  'GOINSECURE',
  'GOMODCACHE',
  'GONOPROXY',
  'GONOSUMDB',
  'GOPATH',
  'GOPRIVATE',
  'GOPROXY',
  'GOROOT',
  'GOSUMDB',
  'GOTELEMETRYDIR',
  'GOTMPDIR',
  'GOTOOLDIR',
  'GOTOOLCHAIN',
  'GOVCS',
  'GOWORK',
  'GYP_DEFINES',
  'GYP_CONFIG_DIR',
  'GYP_GENERATORS',
  'GYP_GENERATOR_OUTPUT',
  'GYP_MSVS_OVERRIDE_PATH',
  'GOOGLE_API_BASE_URL',
  'GOOGLE_API_HOST',
  'GOOGLE_API_CERTIFICATE_CONFIG',
  'GOOGLE_APPLICATION_CREDENTIALS',
  'GOOGLE_CLOUD_LOCATION',
  'GOOGLE_CLOUD_PROJECT',
  'GOOGLE_CLOUD_QUOTA_PROJECT',
  'GOOGLE_EXTERNAL_ACCOUNT_ALLOW_EXECUTABLES',
  'GOOGLE_GENAI_USE_VERTEXAI',
  'GOOGLE_GHA_CREDS_PATH',
  'GOOGLE_LOCATION',
  'GOOGLE_PROJECT_ID',
  'HOME',
  'HTTP_PROXY',
  'HTTPS_PROXY',
  'IDENTITY_ENDPOINT',
  'IDENTITY_HEADER',
  'IDENTITY_SERVER_THUMBPRINT',
  'IMDS_ENDPOINT',
  'LANGFUSE_HOST',
  'LDFLAGS',
  'LDFLAGS_HOST',
  'LITELLM_API_BASE',
  'LINK_HOST',
  'LINK_TARGET',
  'LIBRARY_PATH',
  'LLAMA_BASE_URL',
  'LOCALAPPDATA',
  'LOCALAI_BASE_URL',
  'MAKE',
  'MAKEFLAGS',
  'MAKEFILES',
  'MISTRAL_API_BASE_URL',
  'MISTRAL_API_HOST',
  'METADATA_SERVER_DETECTION',
  'MLFLOW_GATEWAY_URL',
  'MSI_ENDPOINT',
  'MSI_SECRET',
  'NVIDIA_API_BASE_URL',
  'NODE_DEBUG',
  'NODE_DEBUG_NATIVE',
  'NODE_GYP_FORCE_PYTHON',
  'NODEJS_ORG_MIRROR',
  'NODE_EXTRA_CA_CERTS',
  'NODE_OPTIONS',
  'NODE_PATH',
  'NODE_TLS_REJECT_UNAUTHORIZED',
  'NO_PROXY',
  'OLLAMA_BASE_URL',
  'OBJC_INCLUDE_PATH',
  'OPENAI_API_BASE_URL',
  'OPENAI_API_HOST',
  'OPENAI_BASE_URL',
  'OPENAI_CUSTOM_HEADERS',
  'OPENAI_ORGANIZATION',
  'OPENAI_ORG_ID',
  'OPENAI_PROJECT_ID',
  'OPENCLAW_CONFIG_PATH',
  'OPENCLAW_GATEWAY_PORT',
  'OPENCLAW_GATEWAY_URL',
  'OPENCODE_CONFIG',
  'OPENCODE_CONFIG_CONTENT',
  'OPENCODE_CONFIG_DIR',
  'OPENCODE_GIT_BASH_PATH',
  'OTEL_EXPORTER_OTLP_ENDPOINT',
  'PALM_API_HOST',
  'PATH',
  'PATHEXT',
  'PKG_CONFIG',
  'PKG_CONFIG_LIBDIR',
  'PKG_CONFIG_PATH',
  'PKG_CONFIG_SYSROOT_DIR',
  'PERL5LIB',
  'PERL5OPT',
  'PERLLIB',
  'PLAYWRIGHT_BROWSERS_PATH',
  'PLAYWRIGHT_CHROMIUM_DOWNLOAD_HOST',
  'PLAYWRIGHT_DOWNLOAD_HOST',
  'PLAYWRIGHT_FIREFOX_DOWNLOAD_HOST',
  'PLAYWRIGHT_WEBKIT_DOWNLOAD_HOST',
  'PORTKEY_API_BASE_URL',
  'PROMPTFOO_CACHE_PATH',
  'PROMPTFOO_API_KEY',
  'PROMPTFOO_AUTHOR',
  'PROMPTFOO_CACHE_TTL',
  'PROMPTFOO_CA_CERT_PATH',
  'PROMPTFOO_CLOUD_API_URL',
  'PROMPTFOO_CONFIG_DIR',
  'PROMPTFOO_DISABLE_CONVERSATION_VAR',
  'PROMPTFOO_DISABLE_DEBUG_LOG',
  'PROMPTFOO_DISABLE_ERROR_LOG',
  'PROMPTFOO_DISABLE_OBJECT_STRINGIFY',
  'PROMPTFOO_DISABLE_REF_PARSER',
  'PROMPTFOO_DISABLE_SHARING',
  'PROMPTFOO_DISABLE_TEMPLATE_ENV_VARS',
  'PROMPTFOO_DISABLE_TEMPLATING',
  'PROMPTFOO_DISABLE_VAR_EXPANSION',
  'PROMPTFOO_FAILED_TEST_EXIT_CODE',
  'PROMPTFOO_INSECURE_SSL',
  'PROMPTFOO_JKS_CERT_PATH',
  'PROMPTFOO_LOG_DIR',
  'PROMPTFOO_MEDIA_PATH',
  'PROMPTFOO_OTEL_ENDPOINT',
  'PROMPTFOO_PASS_RATE_THRESHOLD',
  'PROMPTFOO_PFX_CERT_PATH',
  'PROMPTFOO_PYTHON',
  'PROMPTFOO_REMOTE_API_BASE_URL',
  'PROMPTFOO_REMOTE_APP_BASE_URL',
  'PROMPTFOO_REMOTE_GENERATION_URL',
  'PROMPTFOO_RUBY',
  'PROMPTFOO_SELF_HOSTED',
  'PROMPTFOO_SHARING_APP_BASE_URL',
  'PROMPTFOO_STRICT_FILES',
  'PROMPTFOO_UNALIGNED_INFERENCE_ENDPOINT',
  'PUPPETEER_CACHE_DIR',
  'PUPPETEER_CHROME_DOWNLOAD_BASE_URL',
  'PUPPETEER_DOWNLOAD_BASE_URL',
  'PUPPETEER_DOWNLOAD_HOST',
  'PUPPETEER_EXECUTABLE_PATH',
  'PYTHONEXECUTABLE',
  'PYTHONHOME',
  'PYTHON',
  'PYTHONPATH',
  'PYTHONSTARTUP',
  'PYTHONUSERBASE',
  'PYTHONWARNINGS',
  '_PYTHON_SYSCONFIGDATA_NAME',
  'REQUESTS_CA_BUNDLE',
  'RUBYGEMS_GEMDEPS',
  'RUBYLIB',
  'RUBYOPT',
  'SHELL',
  'SHAREPOINT_BASE_URL',
  'SHAREPOINT_CERT_PATH',
  'SHAREPOINT_CLIENT_ID',
  'SHAREPOINT_TENANT_ID',
  'SSL_CERT_DIR',
  'SSL_CERT_FILE',
  'SNOWFLAKE_ACCOUNT_IDENTIFIER',
  'USERPROFILE',
  'VERCEL_AI_GATEWAY_BASE_URL',
  'VERTEX_API_HOST',
  'VERTEX_REGION',
  'VERTEX_PROJECT_ID',
  'WATSONX_AI_AUTH_TYPE',
  'WATSONX_AI_BEARER_TOKEN',
  'WATSONX_AI_PROJECT_ID',
  'VOYAGE_API_BASE_URL',
  'XAI_API_BASE_URL',
  'XDG_CONFIG_HOME',
]);

// Cover AWS endpoint overrides plus Bundler, dotenv preload, Google Cloud SDK,
// cgo/native loader (including LD_AUDIT), and git/npm controls inherited by children.
const FORBIDDEN_ENV_FILE_PREFIXES = [
  'AWS_ENDPOINT_URL_',
  'BUNDLE_',
  'CGO_',
  'CLOUDSDK_',
  'DOTENV_CONFIG_',
  'GITHUB_',
  'DYLD_',
  'GIT_',
  'LD_',
  'NPM_CONFIG_',
  'OTEL_EXPORTER_OTLP_',
  'PROMPTFOO_STRIP_',
];

export function findForbiddenEnvFileKey(
  environment: Record<string, string>,
): string | undefined {
  return Object.keys(environment).find((key) => {
    const normalizedKey = key.toUpperCase();
    return (
      FORBIDDEN_ENV_FILE_KEYS.has(normalizedKey) ||
      FORBIDDEN_ENV_FILE_PREFIXES.some((prefix) =>
        normalizedKey.startsWith(prefix),
      )
    );
  });
}

export function loadEnvironmentFile(
  envFilePath: string,
  targetEnvironment: NodeJS.ProcessEnv = process.env,
  override = true,
): void {
  // Parse into an isolated object so untrusted values cannot affect this action
  // or a child process before they have passed the process-control check.
  const fileEnvironment: Record<string, string> = {};
  const result = dotenv.config({
    path: envFilePath,
    override: true,
    processEnv: fileEnvironment,
    quiet: true,
  });

  if (result.error) {
    throw new PromptfooActionError(
      `Failed to load ${envFilePath}: ${result.error.message}`,
      ErrorCodes.ENV_FILE_LOAD_ERROR,
      'Check that the file exists and has valid .env format',
    );
  }

  const forbiddenKey = findForbiddenEnvFileKey(fileEnvironment);
  if (forbiddenKey) {
    throw new PromptfooActionError(
      `Environment file ${envFilePath} sets forbidden process-control variable ${forbiddenKey}`,
      ErrorCodes.INVALID_CONFIGURATION,
      'Remove process, interpreter, provider-endpoint, TLS/proxy, cache/config-path, and pass-rate controls from repository environment files. Configure trusted controls in the workflow environment instead.',
    );
  }

  // Merge into the shared environment (process.env by default) only after the
  // file has fully passed the process-control check. This is deliberate: the
  // action forwards process.env to the promptfoo child. Validation therefore
  // has to happen here, at the untrusted-file boundary — not on the final child
  // environment, which legitimately inherits the trusted runner's own PATH,
  // provider endpoints, cache path, threshold, etc. Preserves the documented
  // later-file-wins ordering for ordinary application variables.
  for (const [key, value] of Object.entries(fileEnvironment)) {
    if (override || targetEnvironment[key] === undefined) {
      targetEnvironment[key] = value;
    }
  }
}
