name: 'build-test'
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  checks: read

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Use Node 24.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24.x'
      - run: npm install -g npm@11.18.0
      - run: npm ci
      - run: npm run all
  style-check:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Use Node 24.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24.x'
      - name: Install npm 11.18.0
        run: npm install -g npm@11.18.0
      - name: Install Dependencies
        run: npm ci
      - name: Run Biome Check
        run: npm run biome:check
